/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xenon.ui_packx;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author xenxi
 */
public class ExitingDialog extends javax.swing.JFrame {

    ExitCommunicationInterface notifier;
    private final int[] DEFAULT_EXIT_DIALOG_SIZE = {375, 156};

    private void intiUserComponents() {
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage(getClass().getResource("LOGO.png")));
        double[] coord = ScreenMatrixUtility.getCenteringLocation(DEFAULT_EXIT_DIALOG_SIZE);
        this.setLocation((int) coord[0], (int) coord[1]);
    }

    public static interface ExitCommunicationInterface {

        void isExited(boolean b);
    }

    public void setNotifier(ExitCommunicationInterface notifier) {
        this.notifier = notifier;
    }

    /**
     * Creates new form ExitingDialog
     */
    public ExitingDialog() {
        intiUserComponents();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitNoBtn = new javax.swing.JButton();
        exitYesBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Exiting Application");
        setUndecorated(true);

        jPanel1.setToolTipText(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Exiting Application");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Do you really want to exit now?");

        exitNoBtn.setBackground(new java.awt.Color(196, 50, 74));
        exitNoBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitNoBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitNoBtn.setText("NO");
        exitNoBtn.setToolTipText(null);
        exitNoBtn.setBorder(null);
        exitNoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitNoBtn.setPreferredSize(new java.awt.Dimension(116, 31));
        exitNoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitNoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitNoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitNoBtnMouseExited(evt);
            }
        });

        exitYesBtn.setBackground(new java.awt.Color(34, 108, 110));
        exitYesBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitYesBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitYesBtn.setText("YES");
        exitYesBtn.setToolTipText(null);
        exitYesBtn.setBorder(null);
        exitYesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitYesBtn.setPreferredSize(new java.awt.Dimension(116, 31));
        exitYesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitYesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitYesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitYesBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(exitNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitYesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitNoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitNoBtnMouseClicked
        notifier.isExited(false);
        this.dispose();
    }//GEN-LAST:event_exitNoBtnMouseClicked

    private void exitNoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitNoBtnMouseEntered
        exitNoBtn.setBackground(new Color(255, 50, 84));
    }//GEN-LAST:event_exitNoBtnMouseEntered

    private void exitNoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitNoBtnMouseExited
        exitNoBtn.setBackground(new Color(196, 50, 74));
    }//GEN-LAST:event_exitNoBtnMouseExited

    private void exitYesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitYesBtnMouseClicked
        notifier.isExited(true);
        this.dispose();
    }//GEN-LAST:event_exitYesBtnMouseClicked

    private void exitYesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitYesBtnMouseEntered
        exitYesBtn.setBackground(new Color(0, 224, 255));
        exitYesBtn.setForeground(new Color(46, 45, 53));
    }//GEN-LAST:event_exitYesBtnMouseEntered

    private void exitYesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitYesBtnMouseExited
        exitYesBtn.setBackground(new Color(34, 108, 110));
        exitYesBtn.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_exitYesBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExitingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExitingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExitingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExitingDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExitingDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitNoBtn;
    private javax.swing.JButton exitYesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
